[build]
  functions = "functions"  # Thư mục chứa các hàm serverless (functions)
  publish = "public"       # Thư mục chứa các tệp tĩnh (HTML, CSS, JS)
  command = "npm run build" # Lệnh xây dựng ứng dụng, nếu cần

[[plugins]]
  package = "@netlify/plugin-nextjs"
